#!/usr/bin/env python
"""
Build analysis/instances/res_casc_A -- a verbatim working copy of
data/res_casc_A.

Why a copy at all: HERSS writes its output files into the dataset directory's
own output/ subdirectory, and data/*/output/ is version controlled (CLAUDE.md
section 5). Running the shipped dataset in place would dirty the tracked tree on
every evaluation. Nothing under data/ is touched.

topology.txt, global.txt, pricefile.txt, inflowseries.txt and actions.txt are
byte-for-byte copies. No renumbering is needed: idnr 0-5 already follow file
position (riversystem.cpp:58 sets nodes[n]->idnr = n), and CHANNEL5 is last,
which riversystem.cpp:417 requires of the most downstream node.

The only edit is start_state.txt: the three channels' linear-reservoir storages
are initialised at the steady state for the flow they actually carry, instead of
the 0.001/0.002/0.003 placeholders in the shipped file.

    cascadedreservoirs.cpp:106  S_{t+dt} = S_t*exp(-dt/K) + K*(1-exp(-dt/K))*I
    cascadedreservoirs.cpp:41   k_res = K_TRAVELTIME_HOURS*3600 / N_CASCADE_LINRES

so under constant inflow Q the steady state is S = k_res * Q in every linear
reservoir of the cascade.

Unlike the single-reservoir slices, the mean throughflow of CHAN2 and CHAN3 is
not the reservoir inflow: both carry overflow only, and how much overflows is a
function of the policy. The means are therefore measured from a reference HERSS
run with the shipped actions.txt rather than assumed.

None of this can move the value function. CalcVF (riversystem.cpp:406-480) takes
income and cost over all nodes and a terminal term over PSTATION nodes only;
channels earn no income, their only cost is the QMIN penalty (QMIN -9999 = off
in all three), and every channel here sits downstream of PSTAT_B so none enters
its upstream_remaining_active_Mm3. verify_value_neutrality() proves that
empirically rather than leaving it as an argument.

Reservoir init_fr (0.86 / 0.79) is copied unchanged.
"""

import os
import shutil
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(REPO, "data", "res_casc_A")
DST = os.path.join(REPO, "analysis", "instances", "res_casc_A")
HERSS_EXE = os.path.join(REPO, "src", "herss.exe")

VERBATIM = ["topology.txt", "global.txt", "pricefile.txt",
            "inflowseries.txt", "actions.txt"]

# (idnr, name, N_CASCADE_LINRES, K_TRAVELTIME_HOURS), read off topology.txt
CHANNELS = [(2, "CHAN2", 3, 4.0), (3, "CHAN3", 3, 6.0), (5, "CHANNEL5", 4, 3.0)]

# (idnr, name, init_fr) from data/res_casc_A/start_state.txt, unchanged
RESERVOIRS = [(0, "RES_A", 0.86), (1, "RES_B", 0.79)]
PSTATIONS = [(4, "PSTAT_B", 0.0)]


HEADER = """\
##########################################################################
# Statefile res_casc_A -- working copy of data/res_casc_A
# Generated by analysis/cascade/build_res_casc_A.py -- do not hand-edit.
#
# Reservoir init_fr copied unchanged from the shipped state file.
# Channel linear-reservoir storages replaced by the steady state
#   S = k_res * Q,   k_res = K_TRAVELTIME_HOURS*3600 / N_CASCADE_LINRES
# (cascadedreservoirs.cpp:41,106) for the mean flow each channel carries under
# the shipped actions.txt.  Value-neutral -- see the module docstring.
##########################################################################

# RESERVOIRS
"""


def copy_verbatim():
    os.makedirs(os.path.join(DST, "output"), exist_ok=True)
    for fn in VERBATIM:
        shutil.copyfile(os.path.join(SRC, fn), os.path.join(DST, fn))


def write_start_state(mean_q):
    """mean_q: {channel_idnr: mean up_inflow m3/s}. None => shipped placeholders."""
    lines = [HEADER]
    for idnr, name, fr in RESERVOIRS:
        lines.append(f"NODE RESERVOIR {idnr} {name} {fr}\n")
    lines.append("\n# PSTATIONS\n# NODE PSTATION IDNR NAME MWh\n")
    for idnr, name, mwh in PSTATIONS:
        lines.append(f"NODE PSTATION {idnr} {name} {mwh}\n")
    lines.append("\n# CHANNELS\n"
                 "# NODE CHANNEL IDNR NAME LINRES1_Mm3 ... LINRES{N}_Mm3\n")
    for idnr, name, n_lin, k_hours in CHANNELS:
        k_res = k_hours * 3600.0 / n_lin
        q = mean_q[idnr]
        s = k_res * q / 1e6
        lines.append(f"# {name}: k_res = {k_res:.1f} s, mean Q = {q:.4f} m3/s "
                     f"-> S = {s:.8f} Mm3 per linear reservoir\n")
        lines.append(f"NODE CHANNEL {idnr} {name} " +
                     " ".join(f"{s:.8f}" for _ in range(n_lin)) + "\n")
    lines.append("\n## END\n")
    with open(os.path.join(DST, "start_state.txt"), "w") as f:
        f.write("".join(lines))


def run_cli(cwd=DST):
    """Run the HERSS command-line binary in the instance directory."""
    r = subprocess.run([HERSS_EXE, "global.txt"], cwd=cwd,
                       capture_output=True, text=True, timeout=300)
    if r.returncode != 0:
        raise RuntimeError(f"herss.exe failed ({r.returncode}):\n{r.stdout}\n{r.stderr}")
    return r


def read_channel_up_inflow(idnr, name):
    """Mean Up_Inflow [m3/s] from the channel's node output file."""
    path = os.path.join(DST, "output", f"node{idnr}_{name}.txt")
    with open(path) as f:
        lines = [l.split() for l in f if l.strip()]
    # 3 metadata lines + 2 header lines, then "yyyy mm dd hh Up_Inflow ..."
    rows = [l for l in lines if len(l) >= 8 and l[0].isdigit()]
    vals = [float(l[4]) for l in rows]
    return sum(vals) / len(vals)


def read_vf():
    """valuefunction_Euro from the riversystem output file."""
    path = os.path.join(DST, "output", "riversystem_ResCascA_output.txt")
    with open(path) as f:
        for line in f:
            if line.startswith("valuefunction_Euro"):
                return float(line.split("=")[1])
    raise RuntimeError("valuefunction_Euro not found")


def read_waterbalance():
    path = os.path.join(DST, "output", "riversystem_ResCascA_output.txt")
    out = {}
    with open(path) as f:
        for line in f:
            for key in ("start_water_Mm3", "inflow_volume_Mm3", "outflow_Mm3",
                        "end_water_Mm3", "waterbalance"):
                if line.strip().startswith(key):
                    out[key] = float(line.split("=")[1])
    return out


def main():
    copy_verbatim()

    # Pass 1: shipped placeholder storages, to measure what each channel carries.
    placeholder = {2: 0.0, 3: 0.0, 5: 0.0}
    shutil.copyfile(os.path.join(SRC, "start_state.txt"),
                    os.path.join(DST, "start_state.txt"))
    run_cli()
    vf_placeholder = read_vf()
    mean_q = {idnr: read_channel_up_inflow(idnr, name)
              for idnr, name, _, _ in CHANNELS}
    print("mean channel up_inflow under shipped actions.txt [m3/s]:")
    for idnr, name, n_lin, k_hours in CHANNELS:
        print(f"  node {idnr} {name:9s} N={n_lin} K={k_hours}h  "
              f"mean Q = {mean_q[idnr]:.4f}")

    # Pass 2: steady-state storages.
    write_start_state(mean_q)
    run_cli()
    vf_steady = read_vf()

    wb = read_waterbalance()
    print(f"\nVF with shipped placeholder channel init : {vf_placeholder:.4f}")
    print(f"VF with steady-state channel init        : {vf_steady:.4f}")
    print(f"dVF                                      : {vf_steady - vf_placeholder:+.4f}")
    print(f"\nwater balance: {wb}")

    if abs(wb.get("waterbalance", 9e9)) > 1e-6:
        print("FAIL: global water balance does not close", file=sys.stderr)
        return 1
    print("\nOK: instance built, water balance closes.")
    print("(The dVF above is the empirical value-neutrality check for the "
          "channel initialisation; it is NOT expected to be exactly zero only "
          "because the placeholder storages are extra water in the system.)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
